#!/usr/bin/env perl

use Modern::Perl;
use Test::More;
use IO::Socket::INET;
use M3MTA::Test::SocketScript;

my $DEBUG = 0;
my $testrun = time . '-' . int(rand(100000));

note "Test run: $testrun";

# for now we'll assume M3MTA is already running
sub get_socket { 
	return M3MTA::Test::SocketScript->get_socket('localhost', 'smtp(25)');
}

# Construct a demo message
my $message = <<EOF
To: <postmaster\@[=host]>\\r\\n
Message-Id: test\@[=host]\\r\\n
Subject: Automated test message (run $testrun)\\r\\n
From: Automated Test <automated\@m3.mta>\\r\\n
Date: Tue 01 Jan 2013 00:00:00 +0000\\r\\n
\\r\\n
Message generated by automated test suite.\\r\\n
\\r\\n
.\\r\\n
EOF
;
# Replace actual newlines so we don't break the test 'script'
$message =~ s/\n//msg;

my @tests = (
	<<EOF
		Successful message delivery
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: MAIL FROM:<>
		R: 250 sender ok
		S: RCPT TO:<postmaster@[=host]>
		R: 250 postmaster@[=host] recipient ok
		S: DATA
		R: 354 Send mail, end with "." on line by itself
		S: $message
		R: 250 [id:"[^\@]+@[=host]"] message accepted for delivery
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		Quit after connection
		R: 220 [host:"[^\\s]+"] M3MTA
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		MAIL before HELO
		R: 220 [host:"[^\\s]+"] M3MTA
		S: MAIL FROM:<>
		R: 503 bad sequence of commands
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		RCPT before HELO
		R: 220 [host:"[^\\s]+"] M3MTA
		S: RCPT TO:<postmaster@[=host]>
		R: 503 bad sequence of commands
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		RCPT before MAIL
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: RCPT TO:<postmaster@[=host]>
		R: 503 send MAIL command first
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		Multiple MAIL commands
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: MAIL FROM:<>
		R: 250 sender ok
		S: MAIL FROM:<>
		R: 250 sender ok
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		DATA before HELO
		R: 220 [host:"[^\\s]+"] M3MTA
		S: DATA
		R: 503 bad sequence of commands
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		DATA before MAIL
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: DATA
		R: 503 send MAIL command first
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		DATA before RCPT
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: MAIL FROM:<>
		R: 250 sender ok
		S: DATA
		R: 503 send RCPT command first
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		Invalid senders
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: MAIL FROM:<
		R: 501 Invalid sender
		S: MAIL FROM:>
		R: 501 Invalid sender
		S: MAIL FROM:Somebody
		R: 501 Invalid sender
		S: MAIL FROM:Somebody<somebody\@somewhere.com>
		R: 501 Invalid sender
		S: MAIL FROM:<somebody>
		R: 501 Invalid sender
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		Invalid recipients
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: MAIL FROM:<>
		R: 250 sender ok
		S: RCPT TO:<
		R: 550 Invalid recipient
		S: RCPT TO:>
		R: 550 Invalid recipient
		S: RCPT TO:Somebody
		R: 550 Invalid recipient
		S: RCPT TO:Somebody<somebody\@somewhere.com>
		R: 550 Invalid recipient
		S: RCPT TO:<somebody>
		R: 550 Invalid recipient
		S: QUIT
		R: 221 Bye.
EOF
	, <<EOF
		Postmaster addresses
		Invalid recipients
		R: 220 [host:"[^\\s]+"] M3MTA
		S: HELO localhost
		R: 250 Hello 'localhost'. I'm M3MTA
		S: MAIL FROM:<>
		R: 250 sender ok
		S: RCPT TO:<postmaster>
		R: 250 postmaster recipient ok
		S: QUIT
		R: 221 Bye.
EOF
);

M3MTA::Test::SocketScript->batch(\&get_socket, @tests);

done_testing();