#!/bin/sh -e

NAME=M3MTA-SMTP

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/m3mta-smtp
export PERL5LIB=/usr/lib/m3mta:${PERL5LIB}
CONFIG=/etc/m3mta/smtp.json
PIDFILE=/var/run/m3mta/smtp.pid
LOGFILE=/var/log/m3mta/smtp.log

ARGS="--daemon --config ${CONFIG} --pidfile ${PIDFILE} --logfile ${LOGFILE}"

. /lib/lsb/init-functions

running() {
    if [ -f ${PIDFILE} ]; then
        echo y
    fi
}

case "$1" in
    start)
        log_daemon_msg "Starting ${NAME}"
        RUNNING=$(running)
        if [ -n "$RUNNING" ]; then
            log_end_msg 0
        else
            if start-stop-daemon --start --pidfile ${PIDFILE} --exec ${DAEMON} -- ${ARGS}; then
                log_end_msg 0
            else
                log_end_msg 1
            fi
        fi
    ;;

    stop)
        RUNNING=$(running)
        log_daemon_msg "Stopping ${NAME}"
        if [ -n "$RUNNING" ]; then
            if ${DAEMON} --stop --pidfile ${PIDFILE}; then
                log_end_msg 0
            else
                log_end_msg 1
            fi
        else
            log_end_msg 0
        fi
    ;;

    restart)
        $0 stop
        $0 start
    ;;

    status)
        RUNNING=$(running)
        if [ -n "$RUNNING" ]; then
           log_success_msg "${NAME} is running"
           exit 0
        else
           log_success_msg "${NAME} is not running"
           exit 3
        fi
    ;;

    flush|check|abort)
        ${DAEMON} $1
    ;;

    *)
        log_action_msg "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
esac

exit 0

